name: bizzio
description: App for freelancers to help with managing projects, clients and invoices.
version: 1.0.0+1
license: "MIT"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.0

  sqflite_common_ffi: ^2.2.0
  path_provider: ^2.0.0
  path: ^1.9.1

  pdf: ^3.8.0
  printing: ^5.10.0
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  file_selector: ^0.9.0

  go_router: ^7.0.0

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/Roboto-Regular.ttf

flutter_test:
  sdk: flutter