name: bizzio
description: App for freelancers to help with managing projects, clients and invoices.
version: 1.0.0+1
license: "MIT"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5

  hive: ^2.0.0
  hive_flutter: ^1.1.0

  path_provider: ^2.0.11

  uuid: ^3.0.6
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_test:
  sdk: flutter